name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Debugging Step 1
        run: echo "Debugging Step 1"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Dependencies with Yarn
        run: yarn install

      - name: Set Environment Variables
        run: |
          echo "Setting environment variables from .env file..."
          echo "VITE_REACT_APP_API_URL=$(cat .env | grep VITE_REACT_APP_API_URL= | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "VITE_REACT_APP_API_URL_DEV=$(cat .env | grep VITE_REACT_APP_API_URL_DEV= | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Build the application
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn run build ||exit 1

      - name: Debugging Step 2
        run: echo "Debugging Step 2"

      - name: Nginx restart
        run: sudo systemctl restart nginx
